### ISSUE TITLE
Switch to Dask theme for Sphinx doc

### ISSUE THREAD

**Issue by balsigergil** [g-roch/heig-bot#14]
Switch to dask theme or keep the readthedoc's theme and update the readme
```
html_theme = 'dask_sphinx_theme'
```

**Comment by g-roch** [comment]
Je pense que dask affiche trop de lien vers dask.org.
Quel avantages vois-tu à dask ?

**Comment by balsigergil** [comment]
Aucun, mais dans ce cas il faut mettre à jour le README.md
